#!/usr/bin/env python3
"""Collect everything the deployment scaffold still needs to know, over SSH.

Read-only. It runs `docker inspect` and reads files; it changes nothing on any
host and touches no container state.

Secrets never leave the host. credentialSecret, adminAuth and anything that
looks like a password, token or bcrypt hash is masked before a settings.js is
written to disk, hashed or printed. flows_cred.json and .config.runtime.json
are never downloaded — only their existence is reported.

Usage
-----
    pip install paramiko
    cp scripts/collect-inventory.py scripts/collect-inventory.local.py
    # fill in HOSTS in the copy — *.local.py is gitignored
    python3 scripts/collect-inventory.local.py

Credentials may also live in a gitignored hosts.local.json next to this file:

    [{"name": "wag-svr-lin01", "ip": "10.60.1.198", "user": "...", "password": "..."}]

which takes precedence over the HOSTS list below. Use `key_file` instead of
`password` for key auth.

Outputs
-------
    inventory/<host>.json                     raw facts per host
    inventory/settings/<instance>.settings.js masked settings.js
    inventory/REPORT.md                       the answers, human-readable
    samples/<instance>.flows.json             real flows, for normalize.py
    registry.draft.yml                        pre-filled registry.yml
"""

from __future__ import annotations

import difflib
import hashlib
import json
import re
import sys
import traceback
from pathlib import Path

# ---------------------------------------------------------------------------
# CONFIG — fill this in, in your gitignored *.local.py copy.
# ---------------------------------------------------------------------------

HOSTS = [
    {"name": "cho-svr-lin01",  "ip": "10.11.1.101",   "user": "", "password": ""},
    {"name": "pod-svr-lin01",  "ip": "10.20.1.160",   "user": "", "password": ""},
    {"name": "jan-svr-lin01",  "ip": "10.30.1.150",   "user": "", "password": ""},
    {"name": "srem-svr-lin01", "ip": "10.40.1.161",   "user": "", "password": ""},
    {"name": "wag-svr-lin01",  "ip": "10.60.1.198",   "user": "", "password": ""},
    {"name": "foi-svr-lnx01",  "ip": "192.168.64.60", "user": "", "password": ""},
    {"name": "gor-svr-lin01",  "ip": "10.87.1.150",   "user": "", "password": ""},
    {"name": "slu-svr-lin02",  "ip": "10.90.1.20",    "user": "", "password": ""},
]

SSH_PORT = 22
TIMEOUT = 20

ROOT = Path(__file__).resolve().parent.parent
INV = ROOT / "inventory"
SAMPLES = ROOT / "samples"

# ---------------------------------------------------------------------------
# Redaction
# ---------------------------------------------------------------------------

SECRET_KEYS = "credentialSecret|password|pass|secret|token|apiKey|api_key|key"
_SECRET_ASSIGN = re.compile(
    rf"""(?P<head>\b({SECRET_KEYS})\b\s*[:=]\s*)(?P<q>["'])(?P<val>[^"']*)(?P=q)""",
    re.IGNORECASE,
)
_BCRYPT = re.compile(r"\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}")


def mask_secrets(text: str) -> str:
    """Replace secret values with a length-preserving marker.

    Keeps the fact that a value exists (and whether it changed length),
    discards the value itself.
    """
    out = _SECRET_ASSIGN.sub(
        lambda m: f"{m.group('head')}{m.group('q')}<masked:{len(m.group('val'))}>{m.group('q')}",
        text,
    )
    return _BCRYPT.sub("<masked:bcrypt>", out)


# Per-instance by nature — masked as well, so the grouping answers
# "is it the same file apart from the fields that must differ".
_PER_INSTANCE = re.compile(
    r"""(?P<head>\b(httpAdminRoot|httpNodeRoot|uiPort|uiHost|flowFile|userDir)\b\s*[:=]\s*)"""
    r"""(?P<q>["'])(?P<val>[^"']*)(?P=q)""",
    re.IGNORECASE,
)


def mask_per_instance(text: str) -> str:
    return _PER_INSTANCE.sub(lambda m: f"{m.group('head')}{m.group('q')}<per-instance>{m.group('q')}", text)


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()[:12]


# Node-RED ships settings.js with every option present but commented out.
# Reading the raw file reports a template default as a live setting, so every
# field is parsed from the stripped text. Trailing comments are left alone —
# stripping them would cut a `//` inside a URL string.
_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.S)
_LINE_COMMENT = re.compile(r"(?m)^[ \t]*//.*$")


def strip_comments(js: str) -> str:
    return _LINE_COMMENT.sub("", _BLOCK_COMMENT.sub("", js))


def semantic(js: str) -> str:
    """What the file configures, with comments, indentation and blank lines gone.

    Two settings.js generated by different Node-RED versions differ in their
    comment blocks and whitespace without configuring anything differently.
    Hashing this instead separates a real difference from a different vintage.
    """
    return re.sub(r"\s+", " ", strip_comments(js)).strip()


# ---------------------------------------------------------------------------
# Flow normalization — a preview of normalize.py, used here to compare
# instances against each other.
# ---------------------------------------------------------------------------

POSITIONAL = ("x", "y", "z", "w", "h")


def normalize_flow(nodes: list) -> list:
    out = []
    for node in nodes:
        if not isinstance(node, dict):
            continue
        clean = {k: v for k, v in node.items() if k not in POSITIONAL}
        out.append(dict(sorted(clean.items())))
    return sorted(out, key=lambda n: str(n.get("id", "")))


def flow_signature(nodes: list) -> str:
    """Identity of the flow's logic, ignoring ids and layout.

    Two instances running the same application produce the same signature
    even though every node id differs.
    """
    shape = sorted(
        (str(n.get("type", "")), str(n.get("name", "")))
        for n in nodes
        if isinstance(n, dict)
    )
    return sha(json.dumps(shape))


# ---------------------------------------------------------------------------
# SSH
# ---------------------------------------------------------------------------

class Remote:
    def __init__(self, cfg):
        import paramiko

        self.name = cfg["name"]
        self.client = paramiko.SSHClient()
        self.client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        kwargs = dict(
            hostname=cfg.get("ip") or cfg["name"],
            port=cfg.get("port", SSH_PORT),
            username=cfg["user"],
            timeout=TIMEOUT,
            banner_timeout=TIMEOUT,
            auth_timeout=TIMEOUT,
        )
        if cfg.get("key_file"):
            kwargs["key_filename"] = cfg["key_file"]
        else:
            kwargs["password"] = cfg["password"]
            kwargs["look_for_keys"] = False
        self.client.connect(**kwargs)
        self.sftp = self.client.open_sftp()

    def run(self, cmd: str) -> str:
        _, stdout, _ = self.client.exec_command(cmd, timeout=TIMEOUT)
        return stdout.read().decode("utf-8", "replace").strip()

    def read(self, container: str, mount: str, filename: str) -> str | None:
        """Read a /data file, preferring the bind mount, falling back to exec."""
        if mount:
            try:
                with self.sftp.open(f"{mount}/{filename}") as fh:
                    return fh.read().decode("utf-8", "replace")
            except IOError:
                pass
        out = self.run(f"docker exec {container} cat /data/{filename} 2>/dev/null")
        return out or None

    def close(self):
        try:
            self.sftp.close()
            self.client.close()
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Per-host collection
# ---------------------------------------------------------------------------

SETTINGS_FIELDS = {
    "httpAdminRoot": r"""httpAdminRoot\s*:\s*["']([^"']*)["']""",
    "flowFile": r"""flowFile\s*:\s*["']([^"']*)["']""",
    "functionExternalModules": r"""functionExternalModules\s*:\s*(true|false)""",
    "flowFilePretty": r"""flowFilePretty\s*:\s*(true|false)""",
}

SETTINGS_PRESENT = ("credentialSecret", "adminAuth", "contextStorage")

# Anything that is a Node-RED runtime, however it is packaged.
RUNTIME_HINT = re.compile(r"node.?red|flowfuse|flowforge", re.I)
FLOWFUSE_HINT = re.compile(r"flowfuse|flowforge", re.I)

# Env var names whose values stay on the host.
SECRET_ENV = re.compile(r"pass|secret|token|key|credential|auth", re.I)


def collect_host(cfg) -> dict:
    host = {"host": cfg["name"], "instances": [], "error": None}
    remote = None
    try:
        remote = Remote(cfg)
        host["fqdn"] = remote.run("hostname -f")

        # Match on the image as well as the container name — a site that named
        # its container something else still runs a node-red image. FlowFuse
        # instances are Node-RED too, under a name that says nothing about it.
        host["all_containers"] = remote.run(
            "docker ps -a --format '{{.Names}}\t{{.Image}}'"
        ).splitlines()
        names = [
            line.split("\t")[0]
            for line in host["all_containers"]
            if RUNTIME_HINT.search(line)
        ]

        # Every service sharing a compose file with Node-RED — the blast
        # radius of a bare `docker compose up -d`.
        host["compose_neighbours"] = {}

        for name in names:
            raw = remote.run(f"docker inspect {name}")
            try:
                info = json.loads(raw)[0]
            except Exception:
                host["instances"].append({"name": name, "error": "docker inspect failed"})
                continue

            cfg_ = info.get("Config", {})
            hostcfg = info.get("HostConfig", {})
            labels = cfg_.get("Labels") or {}
            nets = info.get("NetworkSettings", {}).get("Networks", {}) or {}

            mount = next(
                (m.get("Source") for m in info.get("Mounts", [])
                 if m.get("Destination") == "/data"),
                "",
            )
            compose_file = labels.get("com.docker.compose.project.config_files", "")

            inst = {
                "name": name,
                "host": cfg["name"],
                "image": cfg_.get("Image"),
                "image_pinned": bool(cfg_.get("Image")) and ":" in str(cfg_.get("Image"))
                                and not str(cfg_.get("Image")).endswith((":latest", ":main", ":master")),
                "state": info.get("State", {}).get("Status"),
                "restart_policy": hostcfg.get("RestartPolicy", {}).get("Name"),
                "published_ports": hostcfg.get("PortBindings") or {},
                "dns_search": hostcfg.get("DnsSearch") or [],
                "networks": sorted(nets),
                "ip": next((v.get("IPAddress") for v in nets.values() if v.get("IPAddress")), ""),
                "compose_project": labels.get("com.docker.compose.project"),
                "compose_service": labels.get("com.docker.compose.service"),
                "compose_file": compose_file,
                "data_mount": mount,
            }

            # Filter on the project, not the config_files label — that label can
            # hold a comma-separated list, which an exact-match filter misses,
            # and a silent empty result reads as "nothing else shares the file".
            project = labels.get("com.docker.compose.project")
            if compose_file and project and compose_file not in host["compose_neighbours"]:
                host["compose_neighbours"][compose_file] = sorted(set(
                    remote.run(
                        f"docker ps -a --filter 'label=com.docker.compose.project={project}' "
                        "--format '{{index .Labels \"com.docker.compose.service\"}}'"
                    ).split()
                ))

            # --- FlowFuse ------------------------------------------------------
            # FlowFuse runs Node-RED under its own launcher and can keep the
            # authoritative flow in its platform rather than in /data/flows.json.
            # Nothing here assumes a layout — it reports what is actually there,
            # so the migration off it is designed against facts.
            env_pairs = [e.split("=", 1) for e in (cfg_.get("Env") or []) if "=" in e]
            inst["env"] = {
                k: ("<masked>" if SECRET_ENV.search(k) else v) for k, v in env_pairs
            }
            inst["is_flowfuse"] = bool(
                FLOWFUSE_HINT.search(str(cfg_.get("Image")))
                or FLOWFUSE_HINT.search(json.dumps(labels))
                or any(FLOWFUSE_HINT.search(k) or k.startswith("FORGE_") for k, _ in env_pairs)
            )

            if inst["is_flowfuse"]:
                ff = {"listing": {}}
                for d in ("/data", "/data/.node-red", "/opt/flowforge", "/usr/src/flowforge-nr-launcher"):
                    out = remote.run(f"docker exec {name} sh -lc 'ls -la {d} 2>/dev/null | head -40'")
                    if out:
                        ff["listing"][d] = out.splitlines()
                ff["flow_files"] = remote.run(
                    f"docker exec {name} sh -lc "
                    "'find / -maxdepth 6 -name \"flows*.json\" -not -path \"*/node_modules/*\" "
                    "2>/dev/null | head -20'"
                ).splitlines()
                ff["storage_module"] = remote.run(
                    f"docker exec {name} sh -lc "
                    "'grep -rhoE \"storageModule.{0,60}\" /data/settings.js /usr/src/*/settings.js "
                    "2>/dev/null | head -5'"
                ).splitlines()
                ff["launcher_version"] = remote.run(
                    f"docker exec {name} sh -lc "
                    "'cat /usr/src/*/package.json 2>/dev/null | head -20'"
                ).splitlines()
                ff["node_red_version"] = remote.run(
                    f"docker exec {name} sh -lc "
                    "'node -e \"console.log(require(\\\"node-red/package.json\\\").version)\" 2>/dev/null'"
                )
                inst["flowfuse"] = ff

            # --- settings.js -------------------------------------------------
            # Every field is read from the comment-stripped text. Node-RED ships
            # settings.js with each option present but commented out, so matching
            # the raw file reports a template default as if it were configured.
            settings = remote.read(name, mount, "settings.js")
            if settings:
                masked = mask_secrets(settings)
                live = strip_comments(settings)
                inst["settings"] = {
                    "hash_exact": sha(masked),
                    "hash_ignoring_per_instance": sha(mask_per_instance(masked)),
                    "hash_semantic": sha(semantic(mask_per_instance(masked))),
                    "bytes": len(settings),
                }
                for field, pattern in SETTINGS_FIELDS.items():
                    m = re.search(pattern, live)
                    inst["settings"][field] = m.group(1) if m else None
                for field in SETTINGS_PRESENT:
                    inst["settings"][f"{field}_set"] = bool(
                        re.search(rf"^\s*{field}\s*:", live, re.M)
                    )
                (INV / "settings").mkdir(parents=True, exist_ok=True)
                (INV / "settings" / f"{cfg['name']}__{name}.settings.js").write_text(masked, encoding="utf-8")
            else:
                inst["settings"] = None

            # --- flows.json --------------------------------------------------
            flow_file = (inst.get("settings") or {}).get("flowFile") or "flows.json"
            flows_raw = remote.read(name, mount, flow_file)
            if not flows_raw and flow_file != "flows.json":
                flows_raw = remote.read(name, mount, "flows.json")
            if not flows_raw:
                # Report what is actually in the data directory rather than a bare '?'.
                inst["flows_lookup"] = {
                    "tried": [flow_file, "flows.json"],
                    "data_mount": mount,
                    "listing": remote.run(
                        f"docker exec {name} sh -lc 'ls -la /data 2>/dev/null | head -30'"
                    ).splitlines(),
                    "found": remote.run(
                        f"docker exec {name} sh -lc "
                        "'find /data -maxdepth 2 -name \"*.json\" -not -path \"*/node_modules/*\" "
                        "2>/dev/null | head -20'"
                    ).splitlines(),
                }
            if flows_raw:
                try:
                    nodes = json.loads(flows_raw)
                    norm = normalize_flow(nodes)
                    inst["flows"] = {
                        "bytes": len(flows_raw),
                        "nodes": len(nodes),
                        "normalized_hash": sha(json.dumps(norm, sort_keys=True)),
                        "signature": flow_signature(nodes),
                        "external_modules": sorted({
                            n["module"] for n in nodes
                            if isinstance(n, dict) and n.get("module")
                        }),
                        "node_types": len({
                            n.get("type") for n in nodes if isinstance(n, dict)
                        }),
                    }
                    SAMPLES.mkdir(parents=True, exist_ok=True)
                    (SAMPLES / f"{cfg['name']}__{name}.flows.json").write_text(flows_raw, encoding="utf-8")
                except json.JSONDecodeError as exc:
                    inst["flows"] = {"error": f"unparseable: {exc}"}
            else:
                inst["flows"] = None

            # --- package.json ------------------------------------------------
            pkg = remote.read(name, mount, "package.json")
            if pkg:
                try:
                    inst["palette"] = json.loads(pkg).get("dependencies", {})
                except json.JSONDecodeError:
                    inst["palette"] = {"error": "unparseable"}
            else:
                inst["palette"] = {}

            # --- credential files: existence only ------------------------------
            for f in ("flows_cred.json", ".config.runtime.json"):
                probe = f"test -f '{mount}/{f}'" if mount else f"docker exec {name} test -f /data/{f}"
                inst[f.strip('.').replace('.', '_')] = remote.run(f"{probe} && echo yes || echo no") == "yes"

            # --- Admin API: probe, do not trust settings.js --------------------
            # The admin root is the one field deploy.py cannot get wrong, so it
            # is established empirically: 401 or 200 on <root>/flows is the
            # answer, whatever settings.js appears to say.
            if inst["ip"]:
                parsed = ((inst.get("settings") or {}).get("httpAdminRoot") or "").rstrip("/")
                candidates, seen = [], set()
                for root in (parsed, "", f"/{name}", "/admin", "/node-red", "/nodered"):
                    if root not in seen:
                        seen.add(root)
                        candidates.append(root)
                probes = {}
                for root in candidates:
                    probes[root or "/"] = remote.run(
                        f"curl -s -o /dev/null -m 5 -w '%{{http_code}}' "
                        f"'http://{inst['ip']}:1880{root}/flows' || echo 000"
                    )
                live = [r for r, c in probes.items() if c in ("401", "200")]
                inst["admin_api"] = {
                    "probes": probes,
                    "admin_root": ("" if live and live[0] == "/" else (live[0] if live else None)),
                    "resolved": bool(live),
                    "agrees_with_settings": bool(live) and (live[0].rstrip("/") or "") == parsed,
                }

            # --- Node-RED version ---------------------------------------------
            # Explains why two settings.js differ without either being edited.
            inst["node_red_version"] = remote.run(
                f"docker exec {name} sh -lc "
                "'node -p \"require(\\\"/usr/src/node-red/node_modules/node-red/package.json\\\").version\" "
                "2>/dev/null || node -p \"require(\\\"node-red/package.json\\\").version\" 2>/dev/null'"
            ).strip()

            host["instances"].append(inst)

    except Exception as exc:
        host["error"] = f"{type(exc).__name__}: {exc}"
        traceback.print_exc()
    finally:
        if remote:
            remote.close()
    return host


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def build_report(hosts: list) -> str:
    everything = [i for h in hosts for i in h["instances"] if not i.get("error")]
    flowfuse = [i for i in everything if i.get("is_flowfuse")]
    # FlowFuse instances are a migration source, not a deploy target — they are
    # kept out of the plain-instance analysis so they cannot skew it.
    instances = [i for i in everything if not i.get("is_flowfuse")]
    L = []
    add = L.append

    add("# Inventory report\n")
    add(f"{len(everything)} Node-RED runtimes across "
        f"{len([h for h in hosts if not h['error']])} reachable hosts — "
        f"{len(instances)} plain, {len(flowfuse)} under FlowFuse.\n")

    failed = [h for h in hosts if h["error"]]
    if failed:
        add("## Unreachable hosts\n")
        for h in failed:
            add(f"- **{h['host']}** — {h['error']}")
        add("")

    empty = [h for h in hosts if not h["error"] and not h["instances"]]
    if empty:
        add("## Hosts with no Node-RED container\n")
        add("Everything these hosts do run, so a differently-named instance is visible:\n")
        for h in empty:
            add(f"**{h['host']}**\n")
            add("```")
            L.extend(h.get("all_containers") or ["(no containers at all)"])
            add("```\n")

    # --- FlowFuse ----------------------------------------------------------
    if flowfuse:
        add("## FlowFuse instances — migration source\n")
        add(f"{len(flowfuse)} runtimes run under FlowFuse and are to become plain "
            "Node-RED containers as part of this project. They are excluded from the "
            "analysis below, because they answer different questions.\n")
        add("The decisive one: **where does the authoritative flow live?** If FlowFuse "
            "keeps it in its platform rather than in `/data/flows.json`, the file on disk "
            "is a cache or absent, and the migration is an export from FlowFuse — not a "
            "file copy.\n")
        for i in flowfuse:
            ff = i.get("flowfuse") or {}
            add(f"### {i['host']}/{i['name']}\n")
            add(f"- image: `{i['image']}`")
            add(f"- Node-RED version: `{ff.get('node_red_version') or 'unknown'}`")
            add(f"- storage module: `{'; '.join(ff.get('storage_module') or []) or 'not found in settings.js'}`")
            add(f"- flow files on disk: {', '.join(f'`{p}`' for p in ff.get('flow_files') or []) or '**none found**'}")
            forge = {k: v for k, v in (i.get("env") or {}).items() if k.startswith("FORGE_")}
            if forge:
                add("- FlowFuse env (secret values masked):")
                for k, v in sorted(forge.items()):
                    add(f"  - `{k}` = `{v}`")
            if i.get("palette"):
                add(f"- palette: {', '.join(sorted(i['palette']))}")
            for d, lines in (ff.get("listing") or {}).items():
                add(f"\n<details><summary><code>{d}</code></summary>\n")
                add("```")
                L.extend(lines)
                add("```\n</details>")
            add("")

    # --- Q1: settings.js ---------------------------------------------------
    add("## Q1 — Are the settings.js files the same file?\n")
    add("Plain Node-RED instances only; FlowFuse-managed settings.js files are "
        "generated by the launcher and are not part of this comparison.\n")
    add("Grouped on what the file *configures*: comments, indentation and blank lines "
        "removed, secret values and per-instance fields masked. Node-RED ships every "
        "option commented out and rewrites those comment blocks between versions, so "
        "grouping on the raw text separates files that configure exactly the same thing.\n")

    groups: dict[str, list] = {}
    literal: dict[str, list] = {}
    for i in instances:
        if i.get("settings"):
            groups.setdefault(i["settings"].get("hash_semantic") or "?", []).append(i)
            literal.setdefault(i["settings"]["hash_ignoring_per_instance"], []).append(i)
    if len(groups) == 1:
        add("**One group.** Every settings.js configures the same thing.\n")
        add("→ One template in the repo plus env overrides.\n")
    else:
        add(f"**{len(groups)} groups** by configuration "
            f"({len(literal)} by literal text — the difference is comment and whitespace churn "
            "between Node-RED versions, which needs no reconciling).\n")
        add("→ Reconcile the configuration differences; see the diffs below.\n")
    for idx, (h, members) in enumerate(sorted(groups.items(), key=lambda kv: -len(kv[1])), 1):
        add(f"- group {idx} (`{h}`, {len(members)}): " +
            ", ".join(f"{m['host']}/{m['name']}" for m in members))
    add("")

    if len(groups) > 1:
        add("### Diffs between group representatives\n")
        reps = [members[0] for _, members in sorted(groups.items(), key=lambda kv: -len(kv[1]))]
        base = reps[0]
        base_txt = (INV / "settings" / f"{base['host']}__{base['name']}.settings.js").read_text(encoding="utf-8")
        for other in reps[1:]:
            other_txt = (INV / "settings" / f"{other['host']}__{other['name']}.settings.js").read_text(encoding="utf-8")
            diff = list(difflib.unified_diff(
                strip_comments(mask_per_instance(base_txt)).splitlines(),
                strip_comments(mask_per_instance(other_txt)).splitlines(),
                fromfile=f"{base['host']}/{base['name']}",
                tofile=f"{other['host']}/{other['name']}",
                lineterm="", n=2,
            ))
            add(f"<details><summary>{base['host']}/{base['name']} vs "
                f"{other['host']}/{other['name']} — {len(diff)} diff lines</summary>\n")
            add("```diff")
            L.extend(diff[:200])
            if len(diff) > 200:
                add(f"... {len(diff) - 200} more lines")
            add("```\n</details>\n")

    add("### Per-instance fields\n")
    add("`admin_root` is the probed value — what the running instance actually answers on, "
        "not what settings.js appears to say.\n")
    add("| instance | Node-RED | admin_root (probed) | settings.js says | dns_search | credentialSecret | adminAuth |")
    add("|---|---|---|---|---|---|---|")
    for i in sorted(instances, key=lambda x: (x["host"], x["name"])):
        s = i.get("settings") or {}
        a = i.get("admin_api") or {}
        probed = a.get("admin_root")
        probed_txt = "**unresolved**" if not a.get("resolved") else f"`{probed or '/'}`"
        claimed = s.get("httpAdminRoot")
        flag = "" if a.get("agrees_with_settings") or not a.get("resolved") else " ⚠"
        add(f"| {i['host']}/{i['name']} | {i.get('node_red_version') or '?'} | {probed_txt}{flag} | "
            f"`{claimed or 'unset'}` | {', '.join(i['dns_search']) or '—'} | "
            f"{'set' if s.get('credentialSecret_set') else 'GENERATED'} | "
            f"{'on' if s.get('adminAuth_set') else '**off**'} |")
    add("")
    noauth = [i for i in instances if not (i.get("settings") or {}).get("adminAuth_set")]
    if noauth:
        add(f"**adminAuth is off on {len(noauth)}:** " +
            ", ".join(f"{i['host']}/{i['name']}" for i in noauth) +
            ". Its editor and Admin API are open to anyone who can reach the container.\n")

    # --- Q4/Q5: flows -------------------------------------------------------
    add("## Q4/Q5 — Flow sizes, and which instances share logic\n")
    add("| instance | nodes | bytes | node types | palette | own npm modules |")
    add("|---|---|---|---|---|---|")
    for i in sorted(instances, key=lambda x: (x["host"], x["name"])):
        f = i.get("flows") or {}
        pal = ", ".join(sorted(i.get("palette", {}))) or "—"
        ext = ", ".join(f.get("external_modules", [])) or "—"
        add(f"| {i['host']}/{i['name']} | {f.get('nodes', '?')} | {f.get('bytes', '?')} | "
            f"{f.get('node_types', '?')} | {pal} | {ext} |")
    add("")

    sigs: dict[str, list] = {}
    for i in instances:
        if (i.get("flows") or {}).get("signature"):
            sigs.setdefault(i["flows"]["signature"], []).append(i)
    shared = {s: m for s, m in sigs.items() if len(m) > 1}
    if shared:
        add("Instances running the same logic (matching node type/name multiset, ids and layout ignored):\n")
        for s, members in shared.items():
            add(f"- `{s}`: " + ", ".join(f"{m['host']}/{m['name']}" for m in members))
        add("\n→ Each group becomes one `apps/<name>/` directory.\n")
    else:
        add("No two instances share a flow signature — every instance is a one-off, "
            "so every instance gets its own `apps/` directory or `app: null`.\n")

    ext_users = [i for i in instances if (i.get("flows") or {}).get("external_modules")]
    add(f"Function nodes declaring their own npm module: "
        f"{'NONE — the baked image is a real guarantee' if not ext_users else 'FOUND, see table above'}\n")

    # --- transport ----------------------------------------------------------
    add("## Admin API probe\n")
    add("Each candidate root tried as `<root>/flows`. 401 = reachable, adminAuth active. "
        "200 = reachable, auth off. 404 = the runtime answers but not on that path. "
        "000 = nothing listening.\n")
    add("| instance | probes | resolved root |")
    add("|---|---|---|")
    for i in sorted(instances, key=lambda x: (x["host"], x["name"])):
        a = i.get("admin_api") or {}
        probes = " ".join(f"`{r}`={c}" for r, c in (a.get("probes") or {}).items())
        res = f"`{a.get('admin_root') or '/'}`" if a.get("resolved") else "**none answered**"
        add(f"| {i['host']}/{i['name']} | {probes or '—'} | {res} |")
    add("")
    unresolved = [i for i in instances if not (i.get("admin_api") or {}).get("resolved")]
    if unresolved:
        add(f"**{len(unresolved)} unresolved.** No candidate root answered — the admin root is "
            "something else, or the runtime is not on 1880. These cannot get a `registry.yml` "
            "entry until the root is known.\n")

    missing = [i for i in instances if i.get("flows_lookup")]
    if missing:
        add("## Instances whose flow file was not found\n")
        for i in missing:
            fl = i["flows_lookup"]
            add(f"### {i['host']}/{i['name']}\n")
            add(f"- tried: {', '.join(f'`{t}`' for t in fl['tried'])}")
            add(f"- data mount: `{fl['data_mount'] or 'none — named volume'}`")
            add(f"- json files under /data: {', '.join(f'`{p}`' for p in fl['found']) or 'none'}")
            if fl.get("listing"):
                add("\n```")
                L.extend(fl["listing"])
                add("```")
            add("")

    # --- images and compose --------------------------------------------------
    add("## Image tags and compose blast radius\n")
    add("| instance | image | pinned | restart | published ports | compose service | compose file |")
    add("|---|---|---|---|---|---|---|")
    for i in sorted(instances, key=lambda x: (x["host"], x["name"])):
        add(f"| {i['host']}/{i['name']} | `{i['image']}` | "
            f"{'yes' if i['image_pinned'] else '**NO**'} | {i['restart_policy']} | "
            f"{i['published_ports'] or 'none'} | {i['compose_service']} | `{i['compose_file']}` |")
    add("")
    for h in hosts:
        for f, services in (h.get("compose_neighbours") or {}).items():
            others = [s for s in services if s and not re.search(r"node.?red", s, re.I)]
            if others:
                add(f"- `{h['host']}:{f}` also holds: {', '.join(others)} "
                    f"— a bare `docker compose up -d` recreates these")
    add("")

    add("## Not answerable from the hosts\n")
    add("- **Harbor project for Node-RED images.** Whether a `dap-nodered` project exists "
        "and which GitLab CI variable holds its push credential is a Harbor/GitLab question.\n")
    return "\n".join(L)


def build_registry_draft(hosts: list) -> str:
    L = ["# Generated by scripts/collect-inventory.py — review before use.",
         "# Credential ids and image tags are placeholders.",
         "",
         "global_variables: {}",
         "",
         "instances:"]
    for h in hosts:
        for i in h["instances"]:
            if i.get("error"):
                continue
            a = i.get("admin_api") or {}
            if i.get("is_flowfuse"):
                L.append(f"  # {i['name']} on {h['host']} runs under FlowFuse — migrate it to a")
                L.append(f"  # plain container first, then add it here.")
            L += [
                f"  - name: {i['name']}",
                f"    host: {h['host']}",
                f"    app: null",
                f"    admin_root: {a.get('admin_root') or '/'}"
                + ("" if a.get("resolved") else "  # UNRESOLVED — no candidate root answered"),
                f"    auth_credential_id: CHANGEME-{h['host']}-{i['name']}-auth",
                f"    credential_secret_id: CHANGEME-{h['host']}-{i['name']}-credsecret",
                f"    dns_search: [{', '.join(i['dns_search'])}]",
                f"    image_tag: CHANGEME  # currently running {i['image']}",
                f"    variables: {{}}",
            ]
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------------

def main():
    # Windows consoles default to cp1252; flow node names contain arrows and emoji.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass

    try:
        import paramiko  # noqa: F401
    except ImportError:
        sys.exit("paramiko is missing — run: pip install paramiko")

    local = ROOT / "hosts.local.json"
    targets = json.loads(local.read_text(encoding="utf-8")) if local.exists() else HOSTS
    targets = [t for t in targets if t.get("user") and (t.get("password") or t.get("key_file"))]
    if not targets:
        sys.exit("No credentials configured — fill in HOSTS or create hosts.local.json.")

    INV.mkdir(parents=True, exist_ok=True)
    results = []
    for cfg in targets:
        print(f"[{cfg['name']}] connecting ...", flush=True)
        host = collect_host(cfg)
        n = len([i for i in host["instances"] if not i.get("error")])
        print(f"[{cfg['name']}] {'ERROR: ' + host['error'] if host['error'] else f'{n} instances'}", flush=True)
        (INV / f"{cfg['name']}.json").write_text(json.dumps(host, indent=2, sort_keys=True), encoding="utf-8")
        results.append(host)

    (INV / "REPORT.md").write_text(build_report(results), encoding="utf-8")
    (ROOT / "registry.draft.yml").write_text(build_registry_draft(results), encoding="utf-8")

    flows = sorted(SAMPLES.glob("*.flows.json")) if SAMPLES.exists() else []
    expected = [i for h in results for i in h["instances"]
                if not i.get("error") and (i.get("flows") or {}).get("nodes") is not None]

    print("\n" + "=" * 70)
    print("Wrote:")
    print(f"  {INV / 'REPORT.md'}")
    print(f"  {ROOT / 'registry.draft.yml'}")
    print(f"  {SAMPLES}{'/' if flows else ''}")
    for f in flows:
        print(f"      {f.name}")
    print("=" * 70)

    if len(flows) != len(expected):
        print(f"\nWARNING: {len(expected)} instances returned a flow but {len(flows)} files "
              f"are in {SAMPLES} — something failed to write there.")
    elif flows:
        print(f"\n{len(flows)} flow files. They are in {SAMPLES}, NOT in {INV}.")

    print("\nSend inventory/REPORT.md, and commit samples/ so normalize.py can run against it.")


if __name__ == "__main__":
    main()
