#!/usr/bin/env python3
"""Generate apps/build-image-pipeline.yml from registry.yml.

    python3 scripts/gen-image-pipeline.py           # write it
    python3 scripts/gen-image-pipeline.py --check    # CI: fail if it is stale

One build job and one sign job per app, following the pattern the repository
already used for the frontend image. The file is generated rather than written
by hand for one reason: the image tag in it must be the tag `registry.yml`
pins, and two hand-maintained copies of a version number diverge.

The tag goes in as the buildah component's `image_tag` INPUT. A job-level
`IMAGE_TAG` variable looks like it should work and does nothing: the component
interpolates `$[[ inputs.image_tag ]]` into its own `variables:` at include
time, and reads no variable of that name. That is why every image was pushed
as the commit SHA while registry.yml pinned <version>-<build>.

Builds are also throttled to CONCURRENCY at a time. Twelve buildah jobs at once
saturated the shared runner, and image builds are not urgent enough to be worth
that — a resource group holds one job at a time, so cycling the jobs through
three of them lets three run and queues the rest.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import nodered  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "apps" / "build-image-pipeline.yml"

CONCURRENCY = 3

HEADER = """\
# GENERATED by scripts/gen-image-pipeline.py — do not edit.
# One image per app. The tag comes from registry.yml, so the tag that CI builds
# and the tag that the deploy pins are the same string by construction.
#
# A job only runs when its own app's palette or Dockerfile changed. Twelve
# images rebuilt because one palette moved would be twelve chances for an
# unrelated failure — and a flow commit rebuilding the image would push the
# same pinned tag with different content.
#
# resource_group holds one job per group, so the three groups below cap the
# builds at three at a time. The rest queue as "waiting for resource".

"""


def blocks(instances: list[dict]) -> tuple[list, dict]:
    includes, jobs = [], {}
    for n, inst in enumerate(instances):
        app, tag = inst["app"], inst["image_tag"]
        # harbor.example/dap-node-red/wag-prod:5.0.1-1 -> dap-node-red/wag-prod, 5.0.1-1
        path, _, version = tag.partition(":")
        image_name = "/".join(path.split("/")[1:])

        includes += [
            {"component": "$CI_SERVER_FQDN/infrastructure/ci-cd-catalog/buildah/buildah-build@~latest",
             "inputs": {"stage": "Build", "job_name": f"build:buildah:{app}",
                        "dockerfile": f"apps/{app}/Dockerfile", "image_name": image_name,
                        "image_tag": version, "enable_layers_cache": False}},
            {"component": "$CI_SERVER_FQDN/infrastructure/ci-cd-catalog/cosign/cosign-sign@~latest",
             "inputs": {"stage": "Sign", "job_name": f"sign:cosign:{app}",
                        "image_name": image_name}},
        ]
        # package.json and the Dockerfile are the whole input to this image.
        # apps/<app>/** would include flows.json, and then every flow commit
        # would rebuild and push the SAME pinned tag — a tag whose content
        # changes is not a pinned tag (decision 5).
        rules = [{"if": '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH',
                  "changes": [f"apps/{app}/package.json", f"apps/{app}/Dockerfile"]}]
        jobs[f"build:buildah:{app}"] = {
            # Only the build is throttled. Signing is cheap, and holding it in a
            # group would make it wait behind an unrelated build.
            "resource_group": f"image-build-{n % CONCURRENCY + 1}",
            "rules": rules,
        }
        jobs[f"sign:cosign:{app}"] = {
            "variables": {"IMAGE_TAG": version},
            "needs": [{"job": f"build:buildah:{app}"}],
            "rules": rules,
        }
    return includes, jobs


class NoAliases(yaml.SafeDumper):
    """Emit every rules block in full.

    PyYAML would anchor the identical rule objects and alias the rest. GitLab
    understands anchors, but a reviewer reading `rules: *id009` cannot see what
    a job runs on without scrolling to find the anchor.
    """

    def ignore_aliases(self, data):
        return True


def apps() -> list[dict]:
    return sorted((i for i in nodered.instances() if i.get("app")), key=lambda i: i["app"])


def render() -> str:
    includes, jobs = blocks(apps())
    dump = lambda d: yaml.dump(d, Dumper=NoAliases, sort_keys=False, width=100)
    body = dump({"include": includes}) + "\n" + dump(jobs)
    return HEADER + body


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    want = render()
    if args.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != want:
            print(f"{OUT} is stale — run: python3 scripts/gen-image-pipeline.py", file=sys.stderr)
            return 1
        print(f"{OUT.name} matches registry.yml")
        return 0

    OUT.write_text(want, encoding="utf-8")
    print(f"wrote {OUT} — {len(apps())} images, one per app")
    return 0


if __name__ == "__main__":
    sys.exit(main())
